### ISSUE TITLE
Being official or join to DivestOS?

### ISSUE THREAD

**Issue by sjehuda** [ChzeRub/Lineage-20.0-OTA#1]
Since this ROM is indeed working, why is this not listed in the official website?

Did the LineageOS developers decide to drop support for ARMv7 devides?

References:
- https://wiki.lineageos.org/devices/onyx/
- https://lineageosroms.com/onyx/

Did you think of joining DivestOS?

**Comment by sjehuda** [comment]
@SkewedZeppelin do you have any thoughts on this?

I have tested this ROM and it works nicely.

**Comment by SkewedZeppelin** [comment]
@sjehuda 
LineageOS only officially supports 19.1 or higher devices if they use Linux 4.4 or higher.

onyx is stuck on Linux 3.4.

using a 3.x kernel on Android 12 or higher results in a severely broken network stack among other things.

**Comment by sjehuda** [comment]
I understand.

Actually, there are [comments on XDA](https://xdaforums.com/t/rom-unofficial-lineageos-20-for-onyx.4642371/page-3#post-89452984) about network issues, which I did not experience.

I guess this is the turn of postmarketOS, as far as the kernel is a concern.

Thank you for the comment!

I am closing this subject, albeit, a DivestOS flavour of onyx would be a good thing to have, even if is not official.
